# Generated by Django 6.1 on 2026-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='business_challenge',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='development_approach',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='modules_integration_security',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='outcomes_performance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='proposed_architecture',
            field=models.TextField(blank=True, default=''),
        ),
    ]
