# Generated by Django 5.2.17 on 2026-08-21 09:39

from django.db import migrations, models

def populate_company_info(apps, schema_editor):
    CompanyInformation = apps.get_model('cms', 'CompanyInformation')
    CompanyInformation.objects.create(
        title="Aurexion Technologies",
        slug="aurexion",
        status="published",
        hero={
            "eyebrow": "ABOUT AUREXION",
            "heading": "Engineering the Digital Future of Enterprises",
            "description": "We are an enterprise software solutions and digital transformation platform, building intelligent systems that solve today's most pressing challenges while engineering for scale."
        },
        overview={
            "headline": "Transforming complexity into competitive advantage.",
            "description": [
                "Aurexion delivers premium technology consulting and custom software development to the world's most complex organizations.",
                "Our focus is on engineering excellence across enterprise digital platforms, AI/ML engineering, and cloud modernization."
            ]
        },
        foundation={
            "title": "Built on Engineering Excellence",
            "milestones": [
                {
                    "title": "Foundation of Excellence",
                    "description": "Established with a focus on solving complex enterprise software challenges through rigorous engineering practices."
                },
                {
                    "title": "Digital Transformation Era",
                    "description": "Expanded our capabilities into comprehensive technology consulting and cloud modernization for global operations."
                },
                {
                    "title": "Intelligence & Scale",
                    "description": "Integrated AI/ML engineering into our core offerings, building predictive and automated enterprise platforms."
                }
            ]
        },
        vision={
            "title": "End-to-End Enterprise Transformation Lifecycle",
            "description": "How we translate complex business objectives into resilient, high-velocity digital capabilities.",
            "steps": [
                { "step": "01", "name": "CLIENT", "desc": "Strategic intake & discovery" },
                { "step": "02", "name": "ENGAGEMENT", "desc": "Architecture roadmap & SLAs" },
                { "step": "03", "name": "SOLUTION", "desc": "Bespoke engineering design" },
                { "step": "04", "name": "DELIVERY", "desc": "Agile sprints & CI/CD release" },
                { "step": "05", "name": "OPERATIONS", "desc": "24/7 observability & scaling" },
                { "step": "06", "name": "TRANSFORMATION", "desc": "Enterprise value realized" }
            ]
        },
        mission={
            "title": "Our Mission",
            "description": "To empower enterprises to navigate technological shifts with confidence through scalable software engineering and intelligent digital transformation.",
            "pillars": [
                { "title": "Engineering", "description": "Building resilient custom software solutions.", "icon": "Code" },
                { "title": "Innovation", "description": "Pioneering AI/ML and technology consulting.", "icon": "Cpu" },
                { "title": "Transformation", "description": "Executing seamless cloud modernization.", "icon": "Network" },
                { "title": "Scale", "description": "Architecting scalable technology solutions.", "icon": "Layers" }
            ]
        },
        global_presence={
            "title": "Built for a Global Enterprise Landscape",
            "description": "Architecting solutions that scale across borders with 24/7 follow-the-sun engineering delivery.",
            "hubs": [
                {
                    "region": "Americas Hub",
                    "cities": "San Francisco / New York",
                    "focus": "Enterprise AI & Cloud Architecture",
                    "latency": "<20ms P99",
                    "sla": "99.999%",
                    "status": "ACTIVE NODE"
                },
                {
                    "region": "EMEA Hub",
                    "cities": "London / Zurich",
                    "focus": "Regulatory Systems & Core Banking",
                    "latency": "<15ms P99",
                    "sla": "99.999%",
                    "status": "ACTIVE NODE"
                },
                {
                    "region": "APAC Hub",
                    "cities": "Singapore / Tokyo",
                    "focus": "Edge Networks & Digital Platforms",
                    "latency": "<25ms P99",
                    "sla": "99.999%",
                    "status": "ACTIVE NODE"
                },
                {
                    "region": "India Center of Excellence",
                    "cities": "Hyderabad / Bengaluru",
                    "focus": "Distributed Systems R&D & Scale",
                    "latency": "<30ms P99",
                    "sla": "99.999%",
                    "status": "ACTIVE NODE"
                }
            ]
        },
        leadership={
            "title": "Executive Leadership",
            "items": [
                {
                    "name": "David Vance",
                    "designation": "Chief Executive Officer",
                    "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=85",
                    "bio": "Over 20 years leading global technology consulting firms, spearheading multi-billion-dollar enterprise digital transformations across North America and Europe.",
                    "linkedin": "https://linkedin.com"
                },
                {
                    "name": "Dr. Elena Rostova",
                    "designation": "Chief Technology Officer",
                    "image": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=85",
                    "bio": "Former Principal Architect at Tier-1 cloud platforms. Specializes in distributed systems, zero-trust security infrastructure, and large-scale enterprise AI engineering.",
                    "linkedin": "https://linkedin.com"
                },
                {
                    "name": "Marcus Chen",
                    "designation": "Chief Operating Officer",
                    "image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=85",
                    "bio": "Leads Aurexion's global delivery centers and engineering operations, managing 24/7 follow-the-sun client delivery with strict SLA governance.",
                    "linkedin": "https://linkedin.com"
                }
            ]
        },
        governance={
            "title": "Corporate Governance",
            "nodes": [
                "Security Governance",
                "Access Control",
                "Auditability",
                "Transparency",
                "Enterprise Standards"
            ]
        },
        values={
            "title": "Our Values",
            "items": [
                { "id": "01", "title": "Engineering Excellence" },
                { "id": "02", "title": "Security" },
                { "id": "03", "title": "Transparency" },
                { "id": "04", "title": "Innovation" },
                { "id": "05", "title": "Scalability" },
                { "id": "06", "title": "Client Focus" }
            ]
        },
        security={
            "title": "Security & Trust",
            "items": [
                { "title": "OWASP Top 10", "description": "Strict adherence to secure coding standards.", "icon": "Shield" },
                { "title": "RBAC", "description": "Granular role-based access controls.", "icon": "Users" },
                { "title": "Encryption at Rest", "description": "Data protection across all storage tiers.", "icon": "Lock" },
                { "title": "Encryption in Transit", "description": "End-to-end secure communication.", "icon": "Network" },
                { "title": "Immutable Logs", "description": "Tamper-proof audit trails and tracing.", "icon": "Search" }
            ]
        },
        differentiators={
            "title": "Why Aurexion",
            "items": [
                {
                    "number": "01",
                    "title": "Senior Engineering Focus",
                    "description": "Teams composed of veteran architects and senior developers.",
                    "icon": "Code"
                },
                {
                    "number": "02",
                    "title": "Transparent Delivery",
                    "description": "Complete visibility into our agile processes and code quality.",
                    "icon": "Eye"
                },
                {
                    "number": "03",
                    "title": "IP Security",
                    "description": "Rigorous protection of your intellectual property and data.",
                    "icon": "Lock"
                },
                {
                    "number": "04",
                    "title": "Agile Methodology",
                    "description": "Adaptable execution designed for complex enterprise changes.",
                    "icon": "Zap"
                },
                {
                    "number": "05",
                    "title": "Performance Benchmarks",
                    "description": "Engineering measured against strict operational SLAs.",
                    "icon": "Settings"
                }
            ]
        },
        principles={
            "title": "How We Think",
            "items": [
                {
                    "title": "Engineering Excellence",
                    "description": "Rigorous standards and robust software development practices.",
                    "icon": "Code"
                },
                {
                    "title": "Security",
                    "description": "Security-focused architectures and enterprise-grade protection.",
                    "icon": "Shield"
                },
                {
                    "title": "Scalability",
                    "description": "Systems designed to grow with your enterprise requirements.",
                    "icon": "Scale"
                },
                {
                    "title": "Transparency",
                    "description": "Clear communication and transparent delivery models.",
                    "icon": "Eye"
                },
                {
                    "title": "Agile Delivery",
                    "description": "Iterative, responsive methodology for continuous value.",
                    "icon": "Zap"
                },
                {
                    "title": "Performance",
                    "description": "Measurable technical and business benchmarks.",
                    "icon": "Settings"
                }
            ]
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_casestudy_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aurexion Technologies', max_length=200)),
                ('slug', models.SlugField(default='aurexion', max_length=200, unique=True)),
                ('hero', models.JSONField(blank=True, default=dict)),
                ('overview', models.JSONField(blank=True, default=dict)),
                ('foundation', models.JSONField(blank=True, default=dict)),
                ('vision', models.JSONField(blank=True, default=dict)),
                ('mission', models.JSONField(blank=True, default=dict)),
                ('global_presence', models.JSONField(blank=True, default=dict)),
                ('leadership', models.JSONField(blank=True, default=dict)),
                ('governance', models.JSONField(blank=True, default=dict)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('differentiators', models.JSONField(blank=True, default=dict)),
                ('principles', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.RunPython(populate_company_info),
    ]

