# Generated by Django 5.2.17 on 2026-08-21 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_clientproject_clientdocument_clientrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='delivery_lead_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='portal.clientproject'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='portal.clientproject'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('requirements', 'Project Requirements'), ('architecture', 'Architecture Diagram'), ('sow', 'SOW'), ('report', 'Report'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('deliverable', 'Deliverable'), ('specification', 'Specification'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('enhancement', 'Enhancement'), ('security', 'Security'), ('infrastructure', 'Infrastructure'), ('incident', 'Operational Incident'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ticket_update', 'Ticket Update'), ('project_update', 'Project Update'), ('milestone_update', 'Milestone Update'), ('document_available', 'Document Available'), ('consultation_update', 'Consultation Update')], default='project_update', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('technical_review', 'Technical Review Meeting'), ('status_call', 'Status Call')], default='technical_review', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='portal.clientproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='upcoming', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portal.clientproject')),
            ],
            options={
                'ordering': ['planned_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=255)),
                ('sprint_period', models.CharField(blank=True, default='', max_length=100)),
                ('deliverable_name', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending')], default='completed', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='portal.clientproject')),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
    ]
