# Generated by Django 5.2.16 on 2026-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('authentication', 'Authentication & User Management'), ('recruitment', 'Recruitment & ATS'), ('cms', 'Content Management System'), ('crm', 'Customer Relationship Management'), ('portal', 'Client Portal'), ('administration', 'Administration & Role Management')], max_length=50),
        ),
    ]
