# Generated by Django 5.2.17 on 2026-08-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_modulepermission_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['role', 'module'], name='admin_perm_role_mod_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='admin_role_code_idx'),
        ),
    ]
