# Generated by Django 5.2.16 on 2026-08-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdmFollowUp',
            fields=[
            ],
            options={
                'verbose_name': 'BDM Follow-up Activity',
                'verbose_name_plural': 'BDM Follow-up Activities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.leadfollowup',),
        ),
        migrations.CreateModel(
            name='BdmLead',
            fields=[
            ],
            options={
                'verbose_name': 'BDM Lead Overview',
                'verbose_name_plural': 'BDM Lead Pipeline',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.lead',),
        ),
    ]
