import React from "react";
import { Link } from "wouter";
import { ArrowUpRight, FileText } from "lucide-react";

const LAST_UPDATED = "August 11, 2026";

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    text: "By accessing or using the Aurexion Technologies platform (the 'Platform'), including our website, client portal, estimator tools, RFP submission system, and all related services (collectively, the 'Services'), you agree to be bound by these Terms and Conditions ('Terms'). If you do not agree with any part of these Terms, you must not use the Platform. These Terms apply to all visitors, users, registered clients, and applicants who access or use our Services."
  },
  {
    id: "platform-use",
    title: "2. Permitted Use of the Platform",
    text: "You may use the Platform only for lawful purposes and in accordance with these Terms. You agree not to: (a) use the Platform for any unlawful, fraudulent, or malicious purpose; (b) attempt to gain unauthorised access to any system, data, or user account; (c) transmit any unsolicited commercial communications (spam); (d) submit false, misleading, or fabricated information in any form or submission; (e) reverse-engineer, decompile, or disassemble any part of the Platform; (f) interfere with the performance, security, or integrity of the Platform or its underlying infrastructure."
  },
  {
    id: "ip",
    title: "3. Intellectual Property",
    text: "All content, source code, design assets, trademarks, service marks, logos, and materials on the Platform are the exclusive intellectual property of Aurexion Technologies or its licensors. No content may be copied, reproduced, distributed, republished, downloaded, displayed, posted, or transmitted in any form or by any means without the prior written consent of Aurexion Technologies. You are granted a limited, non-exclusive, non-transferable licence to access and use the Platform solely for its intended purpose."
  },
  {
    id: "submissions",
    title: "4. User Submissions",
    text: "Any information, documents, or content you submit to Aurexion Technologies through the Platform (including RFP submissions, contact forms, job applications, and estimator inputs) is subject to our Privacy Policy. You represent and warrant that all submitted information is accurate, complete, and does not infringe upon the rights of any third party. Aurexion Technologies may use submissions to respond to your enquiry, evaluate your application, and improve its services."
  },
  {
    id: "estimator",
    title: "5. Estimator Disclaimer",
    text: "The Interactive Project Requirement Estimator is provided for preliminary scoping purposes only. Estimates generated by the tool represent indicative budget ranges based on the parameters selected and do NOT constitute a binding quotation, proposal, contract, or financial commitment. Final pricing and timelines are determined exclusively through formal architecture discovery, scope definition, and the issuance of an official Statement of Work (SOW) by Aurexion Technologies."
  },
  {
    id: "confidentiality",
    title: "6. Confidentiality",
    text: "If you share confidential project information, business requirements, or proprietary data with Aurexion Technologies through the Platform (including through the RFP submission system), Aurexion Technologies agrees to treat such information with reasonable confidentiality. If you require a formal Non-Disclosure Agreement (NDA) prior to discussions, please indicate this requirement in your RFP submission or contact our team directly."
  },
  {
    id: "disclaimer",
    title: "7. Disclaimer of Warranties",
    text: "The Platform and all Services are provided on an 'AS IS' and 'AS AVAILABLE' basis without any warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. Aurexion Technologies does not warrant that the Platform will be uninterrupted, error-free, or free of viruses or other harmful components."
  },
  {
    id: "liability",
    title: "8. Limitation of Liability",
    text: "To the fullest extent permitted by applicable law, Aurexion Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, goodwill, or business interruption, arising from your use of or inability to use the Platform, even if Aurexion Technologies has been advised of the possibility of such damages. In no event shall Aurexion Technologies's aggregate liability exceed the amounts paid by you to Aurexion Technologies in the 12 months preceding the claim."
  },
  {
    id: "third-party",
    title: "9. Third-Party Links",
    text: "The Platform may contain links to third-party websites or services. These links are provided for convenience only. Aurexion Technologies has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites. We encourage you to review the terms and privacy policies of any third-party sites you visit."
  },
  {
    id: "termination",
    title: "10. Termination",
    text: "Aurexion Technologies reserves the right to suspend or terminate your access to the Platform at any time, without notice, for conduct that Aurexion Technologies determines, in its sole discretion, violates these Terms, is harmful to other users, Aurexion Technologies, or any third party, or is otherwise inappropriate or unlawful."
  },
  {
    id: "governing-law",
    title: "11. Governing Law",
    text: "These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in San Francisco County, California."
  },
  {
    id: "changes",
    title: "12. Changes to These Terms",
    text: "Aurexion Technologies reserves the right to modify these Terms at any time. We will notify users of material changes by updating the 'Last Updated' date. Your continued use of the Platform following the posting of revised Terms constitutes your acceptance of the changes."
  },
  {
    id: "contact",
    title: "13. Contact",
    text: "If you have questions about these Terms, please contact us at: legal@aurexion.io | Aurexion Technologies, 100 Innovation Way, Suite 400, San Francisco, CA 94105."
  }
];

export const TermsPage: React.FC = () => {
  return (
    <div className="bg-background min-h-screen">
      {/* Hero */}
      <section
        style={{
          background: "linear-gradient(135deg, #050811 0%, #060d1a 50%, #050811 100%)",
          padding: "8rem 0 5rem",
          borderBottom: "1px solid rgba(99,245,232,0.1)",
          position: "relative",
          overflow: "hidden"
        }}
      >
        <div style={{ position: "absolute", inset: 0, backgroundImage: "radial-gradient(ellipse 60% 40% at 30% 50%, rgba(99,245,232,0.04) 0%, transparent 70%)" }} />
        <div style={{ maxWidth: "900px", margin: "0 auto", padding: "0 max(4vw, 1.5rem)", position: "relative" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", marginBottom: "1.5rem" }}>
            <FileText size={14} color="#63f5e8" />
            <span style={{ fontFamily: "'IBM Plex Mono'", fontSize: ".62rem", letterSpacing: ".18em", color: "#63f5e8" }}>LEGAL / TERMS</span>
          </div>
          <h1 style={{ fontSize: "clamp(2.4rem, 5vw, 4rem)", fontWeight: 500, letterSpacing: "-.05em", lineHeight: 1, color: "#eef4f3", margin: "0 0 1.5rem" }}>
            Terms &amp; Conditions
          </h1>
          <p style={{ color: "#8da5ae", lineHeight: 1.7, maxWidth: "600px", fontSize: ".95rem", margin: "0 0 2rem" }}>
            Please read these Terms and Conditions carefully before using the Aurexion Technologies platform. By accessing our services, you agree to be bound by these terms.
          </p>
          <p style={{ fontFamily: "'IBM Plex Mono'", fontSize: ".7rem", color: "#5e7079", letterSpacing: ".05em" }}>
            Last Updated: {LAST_UPDATED}
          </p>
        </div>
      </section>

      {/* Content */}
      <section style={{ maxWidth: "900px", margin: "0 auto", padding: "4rem max(4vw, 1.5rem) 6rem" }}>
        {/* TOC */}
        <div style={{ border: "1px solid rgba(99,245,232,0.12)", background: "#060c18", padding: "2rem", marginBottom: "3rem" }}>
          <p style={{ fontFamily: "'IBM Plex Mono'", fontSize: ".65rem", letterSpacing: ".15em", color: "#63f5e8", marginBottom: "1.2rem" }}>TABLE OF CONTENTS</p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: ".5rem" }}>
            {sections.map(s => (
              <a
                key={s.id}
                href={`#${s.id}`}
                style={{ color: "#8da5ae", fontSize: ".85rem", textDecoration: "none", padding: ".3rem 0" }}
                onMouseOver={e => (e.currentTarget.style.color = "#63f5e8")}
                onMouseOut={e => (e.currentTarget.style.color = "#8da5ae")}
              >
                {s.title}
              </a>
            ))}
          </div>
        </div>

        {sections.map((s, idx) => (
          <div key={s.id} id={s.id} style={{ marginBottom: "3rem", paddingBottom: "3rem", borderBottom: idx < sections.length - 1 ? "1px solid rgba(140,174,187,0.08)" : "none" }}>
            <h2 style={{ fontSize: "1.3rem", fontWeight: 600, color: "#eef4f3", letterSpacing: "-.02em", marginBottom: "1rem" }}>{s.title}</h2>
            <p style={{ color: "#8da5ae", lineHeight: 1.75, fontSize: ".92rem" }}>{s.text}</p>
          </div>
        ))}

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "1rem", marginTop: "2rem" }}>
          <div style={{ display: "flex", gap: "2rem" }}>
            <Link href="/privacy-policy" style={{ fontFamily: "'IBM Plex Mono'", fontSize: ".72rem", color: "#63f5e8", letterSpacing: ".08em", textDecoration: "none" }}>
              PRIVACY POLICY →
            </Link>
            <Link href="/cookie-policy" style={{ fontFamily: "'IBM Plex Mono'", fontSize: ".72rem", color: "#63f5e8", letterSpacing: ".08em", textDecoration: "none" }}>
              COOKIE POLICY →
            </Link>
          </div>
          <Link href="/contact" className="signal-button inline-flex items-center gap-2" style={{ fontSize: ".75rem" }}>
            CONTACT US <ArrowUpRight size={13} />
          </Link>
        </div>
      </section>
    </div>
  );
};

export default TermsPage;
