# Generated by Django 6.1 on 2026-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_casestudy_business_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
