# Generated by Django 5.2.17 on 2026-08-24 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_cms_status_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='cms_blog_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='industry',
            name='cms_ind_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='cms_blogpos_status_327d87_idx',
            old_name='cms_blog_status_category_idx',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='cms.category'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-created_at'], name='cms_blogpos_status_b51cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['status', '-created_at'], name='cms_industr_status_25980e_idx'),
        ),
    ]
