# Generated by Django 5.2.17 on 2026-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_blogpost_options_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.CharField(blank=True, help_text='S3 / Cloud storage URL for cover image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cover_image',
            field=models.CharField(blank=True, help_text='S3 / Cloud storage URL for cover image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='media',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='media',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]

