# Generated by Django 5.2.16 on 2026-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('budget_range', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to='rfps/%Y/%m/')),
                ('nda_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
