# Generated by Django 6.1 on 2026-08-20 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rfpenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rfp_enquiry',
            field=models.OneToOneField(blank=True, help_text='Associated Request for Proposal (RFP) enquiry details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='crm.rfpenquiry'),
        ),
    ]
