# Generated by Django 5.2.17 on 2026-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_leadfollowup_leadnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='Meeting link (Google Meet, Zoom, Teams, etc.)', max_length=500),
        ),
    ]
