# Generated by Django 5.2.17 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_onboarded',
            field=models.BooleanField(default=False, help_text='True once BDM reviews details, onboards client, and dispatches portal credentials.'),
        ),
    ]
