# Generated by Django 5.2.17 on 2026-08-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_merge_0003_estimatorsubmission_0003_lead_rfp_enquiry'),
        ('crm', '0005_lead_client_onboarded'),
    ]

    operations = [
    ]
