# Generated by Django 6.1 on 2026-08-12 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('administrator', 'Administrator'), ('bdm', 'Business Development Manager'), ('sales_executive', 'Sales Executive'), ('hr_manager', 'HR Manager'), ('content_manager', 'Content Manager'), ('support_executive', 'Support Executive'), ('client_user', 'Client User')], default='client_user', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
