# Generated by Django 5.2.17 on 2026-08-21 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auditlog_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'object_id', '-timestamp'], name='auditlog_mod_obj_ts_idx'),
        ),
    ]
