# Generated by Django 5.2.17 on 2026-08-21 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auditlog_auditlog_mod_obj_ts_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('administrator', 'Administrator'), ('bdm', 'Business Development Manager'), ('sales_executive', 'Sales Executive'), ('hr_manager', 'HR Manager'), ('content_manager', 'Content Manager'), ('support_executive', 'Support Executive'), ('client_user', 'Client User')], db_index=True, default='client_user', max_length=50),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='authenticat_role_4d1409_idx'),
        ),
    ]
