# Generated by Django 6.1 on 2026-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='stage',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
