# Generated by Django 5.2.17 on 2026-08-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_modulepermission_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
    ]
