# Generated by Django 5.2.17 on 2026-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_role_options_alter_role_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modulepermission',
            name='admin_perm_role_mod_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='admin_role_name_idx'),
        ),
    ]
