# Generated by Django 5.2.16 on 2026-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_scope', models.CharField(choices=[('web_app', 'Web App'), ('mobile_app', 'Mobile App'), ('enterprise_software', 'Enterprise Software'), ('erp', 'ERP'), ('crm', 'CRM'), ('ai_ml_platform', 'AI/ML Platform'), ('cloud_migration', 'Cloud Migration'), ('saas', 'SaaS')], max_length=50)),
                ('platform_scale', models.CharField(choices=[('multi_tenant_saas', 'Multi-tenant SaaS'), ('internal_enterprise_tool', 'Internal Enterprise Tool'), ('consumer_facing', 'Consumer Facing'), ('cross_platform_mobile', 'Cross-platform Mobile')], max_length=50)),
                ('user_scale', models.CharField(choices=[('<1k', '<1k Users'), ('10k+', '10k+ Users'), ('100k+', '100k+ Users')], max_length=50)),
                ('has_complex_integrations', models.BooleanField(default=False)),
                ('has_soc2', models.BooleanField(default=False)),
                ('has_hipaa', models.BooleanField(default=False)),
                ('has_gdpr', models.BooleanField(default=False)),
                ('has_sla_24_7', models.BooleanField(default=False)),
                ('engineering_effort_hours', models.IntegerField()),
                ('indicative_budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('indicative_budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
