# Generated by Django 6.1 on 2026-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, default='', help_text='Business reason captured when a lead is marked as lost.', max_length=255),
        ),
    ]
