# Generated by Django 5.2.16 on 2026-08-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimatorSubmission',
        ),
    ]
