# Generated by Django 5.2.17 on 2026-08-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_meeting_link_to_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_scope', models.JSONField(default=list)),
                ('platform_scale', models.CharField(default='medium', max_length=50)),
                ('user_scale', models.CharField(default='10k', max_length=50)),
                ('compliance_requirements', models.JSONField(default=list)),
                ('engineering_effort_hours', models.IntegerField(default=0)),
                ('indicative_budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indicative_budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
