# Generated by Django 5.2.17 on 2026-08-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_estimatorsubmission'),
        ('crm', '0003_lead_rfp_enquiry'),
    ]

    operations = [
    ]
