# Generated by Django 5.2.17 on 2026-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_estimatorsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Agreed project cost / deal value.', max_digits=12, null=True),
        ),
    ]
